### ISSUE TITLE
Bug | No messages sent

### ISSUE THREAD

**Issue by Hurdenn** [idkfelix/ValGPT#1]
# Expected Behavior

Once the listener is started and that ValGPT is running, messages should be formed and sent by ValGPT

# Current Behavior

Messages are not sent

## Steps to Reproduce

1. Start the soft
2. Insert GPT Key
3. Start VALORANT
4. Start listener and ValGPT
5. Queue in game
6. Receive message

## Context

* Operating System: Windows 11
* Release : v1.1.0

**Comment by Hurdenn** [comment]
@idkfelix Lmk if you need more info! The project seems fun 😄

**Comment by Unknpwnhamlyn** [comment]
Are messages being received and shown in the software?

**Comment by idkfelix** [comment]
I am unable to recreate this problem. have you tried creating a new OpenAI Key?

**Comment by Hurdenn** [comment]
The messages do appear in the software GUI

**Comment by idkfelix** [comment]
Is your OpenAI account setup as a paid account?, if not the api key wont work

**Comment by Hurdenn** [comment]
> Is your OpenAI account setup as a paid account?, if not the api key wont work

I am so sorry, I feel quite dumb here, thank you, this was indeed the solution!

Though it seems like the soft is now responding to itself, spamming chat with messages hehe

**Comment by idkfelix** [comment]
glad I could help, i've released a hotfix for the chat spam as message Ids were being inconsistently appended resulting in the AI responding multiple times to a single message
