### ISSUE TITLE
BUG | Responding to self

### ISSUE THREAD

**Issue by Hurdenn** [idkfelix/ValGPT#2]
# Expected Behavior
When the user send messages in the chat, ValGPT should not answer. Only messages sent by other players should be answered

# Current Behavior

When the user has an unsupported character in their name, ValGPT answer their messages, then answering those messages, creating an infinite loop.

## Steps to Reproduce

1. Start the soft
2. Insert GPT Key
3. Start VALORANT on an account with an unsupported character (eg: C**é**leste)
4. Start listener and ValGPT
5. Queue in game
6. Receive message or send a message

## Context

* Operating System: Windows 11
* Release : v1.1.0

**Comment by idkfelix** [comment]
does your username in game contain special or non alphanumeric characters?

**Comment by Hurdenn** [comment]
Yes it does "é"

**Comment by idkfelix** [comment]
this probably originates from the username being used as is
```
const username = await getUsername(lockData)
```
and the the message author name being fixed to the openAI specs
```
const unfixedName = msg["game_name"];
const name = unfixedName.replace(/[^a-zA-Z0-9_-]/g, '_');
```

**Comment by idkfelix** [comment]
Published a new release that should fix the mismatch
[https://github.com/idkfelix/ValGPT/releases/tag/v1.1.2](https://github.com/idkfelix/ValGPT/releases/tag/v1.1.2)
